version: '3'

services:
  mysql:
    image: mariadb:10.5 
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p $$MYSQL_ROOT_PASSWORD

  mysql_seeding:
    container_name: mysql_seeding
    build: ./local-dev/mysql-seeding
    volumes:
      - ./local-dev/mysql-seeding:/mysql-seeding
    depends_on:
      - mysql  

  seeding_test:
    container_name: mysql_seeding_test
    build: ./local-dev/tests
    volumes: 
      - ./local-dev/tests:/tests
    depends_on:
      - mysql_seeding
    links:
      - "mysql_seeding:mysql_seeding"