version: '3'

services:
  mysql:
    image: mariadb:10.5 
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"

  mysql_seeding:
    container_name: mysql_seeding
    build: ./local-dev/mysql-seeding
    depends_on:
      - mysql  
