name: run-tests

on:
  push:
    branches: master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build containers
      run: docker-compose -f docker-compose.cli.yaml up -d
    - name: Start db
      run: docker start mysql_db
    - name: Seed db mock entries
      run: docker start mysql_seeding
    - name: Run tests
      run: docker start mysql_seeding_test